import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    margin: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    flexDirection: 'column',
  },
  header: {
    textAlign: 'center',
    marginBottom: 5,
    margin: 5,
  },
  username: {
    fontWeight: 'bold',
    textAlign: 'left',
    fontSize: 20,
    position: 'relative',
    backgroundColor: 'white',
    top: 45,
    left: 10,
    margin: 5,
  },
  login: {
    fontWeight: 'bold',
    textAlign: 'left',
    fontSize: 20,
    position: 'relative',
    backgroundColor: 'white',
    top: 15,
    left: 10,
    margin: 5,
  },
  welcome: {
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 30,
    position: 'relative',
    backgroundColor: '#00BCF4',
    top: 15,
    margin: 5,
  },
  Hello: {
    fontWeight: 'bold',
    textAlign: 'left',
    fontSize: 30,
    color: 'black',
    position: 'relative',
    backgroundColor: 'white',
    top: 15,
    margin: 5,
  },
  quizzy: {
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 40,
    position: 'relative',
    backgroundColor: '#00BCF4',
    color: 'white',
    top: 15,
    margin: 5,
  },
  cardCollection: {
    flex: 0,
    justifyContent: 'flex-start',
    flexDirection: 'column',
    borderWidth: 1,
    marginTop: 10,
    borderColor: 'black',
    borderRadius: 1,
  },
  question: {
    borderWidth: 1,
    margin: 5,
    borderColor: 'black',
    borderRadius: 2,
    alignSelf: 'stretch',
    backgroundColor: '#00BCF4',
  },
  scoreHeading: {
    alignSelf: 'stretch',
    textAlign: 'center',
    margin: 20,
    fontSize: 20,
    color: '#F4810B',
    backgroundColor: 'white',
  },
  score: {
    margin: 20,
    alignSelf: 'stretch',
    textAlign: 'center',
    fontSize: 60,
    color: 'black',
    backgroundColor: 'white',
  },
  leaderBoard: {
    margin: 20,
    alignSelf: 'stretch',
    textAlign: 'center',
    fontSize: 40,
    color: 'black',
    backgroundColor: 'white',
  },
  leader: {
    borderWidth: 1,
    margin: 5,
    borderColor: 'black',
    borderRadius: 2,
    alignSelf: 'stretch',
    backgroundColor: '#00BCF4',
  },
  leaderScore: {
    position: 'relative',
    backgroundColor: '#00BCF4',
  },
});
export default styles;
